<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="30294" started-at="2017-12-07T14:08:52Z" finished-at="2017-12-07T14:09:23Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="30294" started-at="2017-12-07T14:08:52Z" finished-at="2017-12-07T14:09:23Z">
      <class name="Test">
        <test-method status="PASS" signature="extentSetup()[pri:0, instance:Test@7d9d1a19]" name="extentSetup" is-config="true" duration-ms="6371" started-at="2017-12-07T09:08:52Z" finished-at="2017-12-07T09:08:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentSetup -->
        <test-method status="FAIL" signature="passFailed()[pri:0, instance:Test@7d9d1a19]" name="passFailed" duration-ms="37" started-at="2017-12-07T09:08:59Z" finished-at="2017-12-07T09:08:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at Test.passFailed(Test.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- passFailed -->
        <test-method status="PASS" signature="setResult(org.testng.ITestResult)[pri:0, instance:Test@7d9d1a19]" name="setResult" is-config="true" duration-ms="31" started-at="2017-12-07T09:08:59Z" finished-at="2017-12-07T09:08:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=passFailed status=FAILURE method=Test.passFailed()[pri:0, instance:Test@7d9d1a19] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setResult -->
        <test-method status="PASS" signature="passPassed()[pri:0, instance:Test@7d9d1a19]" name="passPassed" duration-ms="0" started-at="2017-12-07T09:08:59Z" finished-at="2017-12-07T09:08:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- passPassed -->
        <test-method status="PASS" signature="passTest()[pri:0, instance:Test@7d9d1a19]" name="passTest" duration-ms="22748" started-at="2017-12-07T09:08:59Z" finished-at="2017-12-07T09:09:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- passTest -->
        <test-method status="PASS" signature="setResult(org.testng.ITestResult)[pri:0, instance:Test@7d9d1a19]" name="setResult" is-config="true" duration-ms="0" started-at="2017-12-07T09:08:59Z" finished-at="2017-12-07T09:08:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=passPassed status=SUCCESS method=Test.passPassed()[pri:0, instance:Test@7d9d1a19] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setResult -->
        <test-method status="PASS" signature="setResult(org.testng.ITestResult)[pri:0, instance:Test@7d9d1a19]" name="setResult" is-config="true" duration-ms="2" started-at="2017-12-07T09:09:22Z" finished-at="2017-12-07T09:09:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=passTest status=SUCCESS method=Test.passTest()[pri:0, instance:Test@7d9d1a19] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setResult -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:Test@7d9d1a19]" name="endTest" is-config="true" duration-ms="1001" started-at="2017-12-07T09:09:22Z" finished-at="2017-12-07T09:09:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- Test -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
